version: '3'

services:
  redis:
    build: redis
    image: redis
    command: redis-server -p 6379
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
    env_file: .env
    environment:
      - MASTER
      - MEMORY

  sentinel:
    build: sentinel
    image: redis-sentinel
    ports:
      - 26379:26379
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
    env_file: .env
    environment:
      - MASTER_NAME=mymaster
      - QUORUM
      - MASTER
      - ANNOUNCE_IP
      - SLAVES
      - DOWN_AFTER=5000
      - FAILOVER_TIMEOUT=10000
    depends_on:
      - redis
