version: '3'

services:
  redis:
    image: redis:4.0.10-alpine
    ports:
      - 6379:6379

  sentinel:
    image: s7anley/redis-sentinel-docker:4.0.10
    ports:
      - 26379:26379
    env_file: .env
    environment:
      - MASTER_NAME=mymaster
      - QUORUM
      - MASTER
      - ANNOUNCE_IP
      - SLAVES
    depends_on:
      - redis
